baseURL = "https://ourxthreee.github.io/"
languageCode = "en-us"
title = "Gallery"
theme = "gallery"
copyright = "© ourxthreee"
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = "120s"

[params]
  defaultTheme = "dark"
  description = "site for ourxthreee-gallery"
  [params.author]
    email = "ourxthreee@proton.me"
    name = "qns-ch"
  [params.socialIcons]
    instagram = "https://www.instagram.com/"
    github = "https://github.com/ourxthreee/"
    email = "mailto:ourxthreee@proton.me"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"
